name: Build CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Code
     
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
       
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
     
      - name: Restore NuGet Packages
        run: nuget restore SignalR.Couchbase.sln

      - name: Build
        run: msbuild SignalR.Couchbase.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

      - name: Publish Web App
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "TEST - {workflow} has {status_message} - {repo_url}"
          message_format: "TEST - {semoji} *{workflow}* {status_message} in <{repo_url}|{repo}@{branch}>"
          notify_when: "success,failure,cancelled,warnings"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DA_SLACK_WEBHOOK_URL }}